#define _CRT_SECURE_NO_WARNINGS 1
#include<stdio.h>
int main() {
	int day = 0;
	while (1) {
		scanf("%d", &day);
		switch (day) {
		case 1:
		case 2:
		case 3:
		case 4:
		case 5:
			printf("工作日\n");
			break;
		case 6:
		case 7:
			printf("休息日\n");
			break;
		default:
			printf("请重新输入\n");
		}
		if (day >= 1 && day <= 7)
			break;
		else
			;
	}
	return 0;
}
